# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'money-spender' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for money-spender
pod 'SnapKit', '~> 5.0.0'
pod 'IQKeyboardManagerSwift', '6.3.0'
end
